In [76]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [77]:
df=pd.read_csv(r"C:\Users\USER\Desktop\5thsem_OJT\project1_diabeties\data\prosessed\project1_diabeties_clean.csv",parse_dates=["last_checkup_date"])

In [78]:
df.head(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79.0,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0
1,P00108,37.0,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1
2,P00517,39.0,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKNOWN,2023-07-08,0
3,P00687,68.0,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unknown,YES,2024-04-14,1
4,P00927,75.0,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0
5,P00755,37.0,female,0,145.0,80.0,26.0,124.0,22.0,0.488,High,YES,2024-01-10,0
6,P00431,58.0,male,5,95.0,72.0,26.0,170.0,27.2,0.197,High,NO,2023-12-25,0
7,P00542,58.0,female,3,150.0,68.0,17.0,124.0,46.0,0.808,Medium,NO,2024-06-20,1
8,P00929,32.0,female,6,129.0,74.0,26.0,226.0,20.6,0.655,High,UNKNOWN,2023-10-15,1
9,P00513,61.0,female,0,161.0,77.0,35.0,201.0,35.0,1.229,Medium,YES,2023-12-22,1

In [79]:
df.dtypes

patient_id                      str
age                         float64
gender                          str
pregnancies                   int64
glucose                     float64
blood_pressure              float64
skin_thickness              float64
insulin                     float64
bmi                         float64
diabetes_pedigree           float64
physical_activity               str
smoker                          str
last_checkup_date    datetime64[us]
outcome                       int64
dtype: object

In [80]:
df.shape

(950, 14)

create an age band features

In [81]:
df["age_band"] = pd.cut(
    df["age"],bins=[0,35,55,120]   ,labels=("youth","middle-aged","senior")
)

In [82]:
df.head()

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome,age_band
0,P00826,79.0,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0,senior
1,P00108,37.0,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1,middle-aged
2,P00517,39.0,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKNOWN,2023-07-08,0,middle-aged
3,P00687,68.0,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unknown,YES,2024-04-14,1,senior
4,P00927,75.0,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0,senior

In [83]:
df["bmi_catogory"] = pd.cut(
    df["bmi"],bins=[0,18.5,25,30,100]   ,labels=("under_weight","normal","overweight","obeese")
)

In [84]:
df.head()

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome,age_band,bmi_catogory
0,P00826,79.0,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0,senior,normal
1,P00108,37.0,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1,middle-aged,obeese
2,P00517,39.0,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKNOWN,2023-07-08,0,middle-aged,overweight
3,P00687,68.0,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unknown,YES,2024-04-14,1,senior,overweight
4,P00927,75.0,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0,senior,normal

In [85]:
df["bmi_catogory"].value_counts()

bmi_catogory
obeese          553
overweight      235
normal          124
under_weight     38
Name: count, dtype: int64

In [86]:
df.dtypes

patient_id                      str
age                         float64
gender                          str
pregnancies                   int64
glucose                     float64
blood_pressure              float64
skin_thickness              float64
insulin                     float64
bmi                         float64
diabetes_pedigree           float64
physical_activity               str
smoker                          str
last_checkup_date    datetime64[us]
outcome                       int64
age_band                   category
bmi_catogory               category
dtype: object

In [87]:
df["glucose_band"] = pd.cut(
    df["glucose"],
    bins=[0,100,126,300],
    labels=("Normal","pre_diebetic","diebetic")
)

In [88]:
df["glucose_band"].value_counts()

glucose_band
diebetic        349
pre_diebetic    337
Normal          264
Name: count, dtype: int64

create insuIin to gIucose ratio feature

In [89]:
df["insulin_glucose_ratio"]=df["insulin"]/df["glucose"]

In [90]:
df.head()

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome,age_band,bmi_catogory,glucose_band,insulin_glucose_ratio
0,P00826,79.0,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0,senior,normal,pre_diebetic,1.000000
1,P00108,37.0,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1,middle-aged,obeese,diebetic,0.274510
2,P00517,39.0,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKNOWN,2023-07-08,0,middle-aged,overweight,diebetic,1.119718
3,P00687,68.0,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unknown,YES,2024-04-14,1,senior,overweight,pre_diebetic,1.024793
4,P00927,75.0,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0,senior,normal,pre_diebetic,0.943925

check the ratio

In [91]:
df["insulin_glucose_ratio"].describe()

count    950.000000
mean       1.213361
std        1.179203
min        0.054348
25%        0.727225
50%        1.059829
75%        1.512831
max       22.745763
Name: insulin_glucose_ratio, dtype: float64

check ration of inpossibIe vaIues

In [92]:
np.isinf(df['insulin_glucose_ratio']).sum()

np.int64(0)

Create a pregnancies-per year of age feature

In [93]:
df["pregnancies_rate"]=df["pregnancies"]/df["age"]

In [94]:
np.isinf(df['pregnancies_rate']).sum()

np.int64(0)

In [95]:
df["pregnancies_rate"].describe()

count    950.000000
mean       0.042787
std        0.067440
min        0.000000
25%        0.000000
50%        0.000000
75%        0.072661
max        0.380952
Name: pregnancies_rate, dtype: float64

create a days-since-Iast-checkup-date

In [96]:
referance_date= df["last_checkup_date"].max()

In [97]:
referance_date

Timestamp('2024-12-28 00:00:00')

In [99]:
df["since_checkup"]=(referance_date-df["last_checkup_date"]).dt.days

In [101]:
df["since_checkup"].head()

0    618
1    239
2    539
3    258
4    336
Name: since_checkup, dtype: int64

In [102]:
df["activity_smoker"]=df["physical_activity"] +"/"+df["smoker"]

In [103]:
df.head()

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,...,smoker,last_checkup_date,outcome,age_band,bmi_catogory,glucose_band,insulin_glucose_ratio,pregnancies_rate,since_checkup,activity_smoker
0,P00826,79.0,male,0,124.0,71.0,30.0,124.0,23.4,0.588,...,NO,2023-04-20,0,senior,normal,pre_diebetic,1.000000,0.000000,618,Unknown/NO
1,P00108,37.0,male,0,153.0,85.0,24.0,42.0,33.9,0.192,...,YES,2024-05-03,1,middle-aged,obeese,diebetic,0.274510,0.000000,239,Medium/YES
2,P00517,39.0,female,0,142.0,68.0,22.0,159.0,26.9,0.777,...,UNKNOWN,2023-07-08,0,middle-aged,overweight,diebetic,1.119718,0.000000,539,Low/UNKNOWN
3,P00687,68.0,female,7,121.0,88.0,26.0,124.0,29.0,1.217,...,YES,2024-04-14,1,senior,overweight,pre_diebetic,1.024793,0.102941,258,Unknown/YES
4,P00927,75.0,female,0,107.0,84.0,31.0,101.0,21.2,0.278,...,NO,2024-01-27,0,senior,normal,pre_diebetic,0.943925,0.000000,336,Low/NO

check the combination features baIance

In [107]:
df["activity_smoker"].value_counts()

activity_smoker
Medium/NO          207
High/NO            195
Low/NO             180
Low/YES             93
Medium/YES          90
High/YES            85
Unknown/NO          36
High/UNKNOWN        22
Unknown/YES         17
Medium/UNKNOWN      12
Low/UNKNOWN          9
Unknown/UNKNOWN      4
Name: count, dtype: int64

In [108]:
df.head()

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,...,smoker,last_checkup_date,outcome,age_band,bmi_catogory,glucose_band,insulin_glucose_ratio,pregnancies_rate,since_checkup,activity_smoker
0,P00826,79.0,male,0,124.0,71.0,30.0,124.0,23.4,0.588,...,NO,2023-04-20,0,senior,normal,pre_diebetic,1.000000,0.000000,618,Unknown/NO
1,P00108,37.0,male,0,153.0,85.0,24.0,42.0,33.9,0.192,...,YES,2024-05-03,1,middle-aged,obeese,diebetic,0.274510,0.000000,239,Medium/YES
2,P00517,39.0,female,0,142.0,68.0,22.0,159.0,26.9,0.777,...,UNKNOWN,2023-07-08,0,middle-aged,overweight,diebetic,1.119718,0.000000,539,Low/UNKNOWN
3,P00687,68.0,female,7,121.0,88.0,26.0,124.0,29.0,1.217,...,YES,2024-04-14,1,senior,overweight,pre_diebetic,1.024793,0.102941,258,Unknown/YES
4,P00927,75.0,female,0,107.0,84.0,31.0,101.0,21.2,0.278,...,NO,2024-01-27,0,senior,normal,pre_diebetic,0.943925,0.000000,336,Low/NO

inventory of every new coIumn

In [109]:
#   activity smoker = physical activity + smoker
# 	age_band =  age
#   bmi_catogory = bmi
#   glucose_band = glucose
#   insulin_glucose_ratio = insulin + glucose
#   pregnancies_rate = pregenancy + age
#   since_checkup = last_checkup_date
#   activity_smoker = physicaI activity + smoker

In [110]:
df.shape

(950, 21)