In [43]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [44]:
df = pd.read_csv(r"C:\Users\USER\Desktop\5thsem_OJT\project1_diabeties\data\prosessed\fizan_P1W2_features.csv")

In [45]:
df["outcome"].value_counts(normalize=True)

outcome
0    0.712632
1    0.287368
Name: proportion, dtype: float64

seperate the features from the target

In [46]:
feature_cols = ["age","pregnancies","glucose","blood_pressure","skin_thickness","insulin","bmi","diabetes_pedigree","bmi_catogory","glucose_band"]

x = df[feature_cols].copy()
y = df["outcome"]

In [47]:
y

0      0
1      1
2      0
3      1
4      0
      ..
945    0
946    1
947    0
948    0
949    0
Name: outcome, Length: 950, dtype: int64

In [48]:
x

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi_catogory,glucose_band
0,79.0,0,124.0,71.0,30.0,124.0,23.4,0.588,normal,pre_diebetic
1,37.0,0,153.0,85.0,24.0,42.0,33.9,0.192,obeese,diebetic
2,39.0,0,142.0,68.0,22.0,159.0,26.9,0.777,overweight,diebetic
3,68.0,7,121.0,88.0,26.0,124.0,29.0,1.217,overweight,pre_diebetic
4,75.0,0,107.0,84.0,31.0,101.0,21.2,0.278,normal,pre_diebetic
...,...,...,...,...,...,...,...,...,...,...
945,64.0,2,117.0,81.0,34.0,124.0,40.3,0.641,obeese,pre_diebetic
946,71.0,0,140.0,64.0,37.0,124.0,33.4,0.116,obeese,diebetic
947,40.0,0,130.0,73.0,26.0,258.0,20.1,0.709,normal,diebetic
948,52.0,4,123.0,76.0,22.0,189.0,38.9,0.540,obeese,pre_diebetic
949,42.0,0,114.0,73.0,34.0,124.0,28.2,0.819,overweight,pre_diebetic

encode your banded features

In [49]:
x = pd.get_dummies(x,drop_first=True)

In [50]:
x.shape

(950, 13)

In [51]:
x

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi_catogory_obeese,bmi_catogory_overweight,bmi_catogory_under_weight,glucose_band_diebetic,glucose_band_pre_diebetic
0,79.0,0,124.0,71.0,30.0,124.0,23.4,0.588,False,False,False,False,True
1,37.0,0,153.0,85.0,24.0,42.0,33.9,0.192,True,False,False,True,False
2,39.0,0,142.0,68.0,22.0,159.0,26.9,0.777,False,True,False,True,False
3,68.0,7,121.0,88.0,26.0,124.0,29.0,1.217,False,True,False,False,True
4,75.0,0,107.0,84.0,31.0,101.0,21.2,0.278,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,64.0,2,117.0,81.0,34.0,124.0,40.3,0.641,True,False,False,False,True
946,71.0,0,140.0,64.0,37.0,124.0,33.4,0.116,True,False,False,True,False
947,40.0,0,130.0,73.0,26.0,258.0,20.1,0.709,False,False,False,True,False
948,52.0,4,123.0,76.0,22.0,189.0,38.9,0.540,True,False,False,False,True
949,42.0,0,114.0,73.0,34.0,124.0,28.2,0.819,False,True,False,False,True

spIit into training and testing  sets

In [53]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,y, test_size=0.2, random_state=42, stratify=y
)

In [55]:
x_test.shape

(190, 13)

confirm the spIit behaved

In [56]:
x_train.shape

(760, 13)

In [58]:
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

outcome
0    0.713158
1    0.286842
Name: proportion, dtype: float64
outcome
0    0.710526
1    0.289474
Name: proportion, dtype: float64